site_name: Today I Learned
site_url: https://iphils.github.io/til/
repo_url: https://github.com/iphils/til
repo_name: iphils/til

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - search.suggest
    - search.highlight

nav:
  - Home: index.md

plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
      strict: false
